### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
Stepping stone for #20 so we can enable tests there.

### CODE REVIEW

**Comment by gforcada** [comment]
🗒️  once this is merged, this repository needs to be added on the [linting global workflow](https://github.com/organizations/plone/settings/actions)

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
One robot failure. Ignore.

**Comment by mauritsvanrees** [comment]
I have added it to the global workflows

**Pull request merged**
